services:
    ns.filtered_pagination:
        class: NS\FilteredPaginationBundle\FilteredPagination
        arguments: [ "@knp_paginator", "@form.factory", "@lexik_form_filter.query_builder_updater" ]
